/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Firma;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Enis Lushtaku
 */
public class FirmaHinzufuegenDlg extends javax.swing.JDialog
{

    private Boolean isOK;
    private Firma firma;

    public Boolean getIsOK()
    {
        return isOK;
    }

    public Firma getFirma()
    {
        return firma;
    }

    /**
     * Creates new form FirmaHinzufuegenDlg
     */
    public FirmaHinzufuegenDlg(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.setTitle("Firma hinzufügen");
        this.setSize(280, 300);
        this.setLocationRelativeTo(null);
        isOK = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        tfFirmenname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfFirmenlogo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btHinzufuegen = new javax.swing.JButton();
        btAbbrechen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Firmenname:  ");
        getContentPane().add(jLabel1);

        tfFirmenname.setText("Magna Steyr");
        getContentPane().add(tfFirmenname);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Firmenlogo:  ");
        getContentPane().add(jLabel2);

        tfFirmenlogo.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfFirmenlogo.setForeground(new java.awt.Color(102, 102, 102));
        tfFirmenlogo.setText("(Optional)");
        getContentPane().add(tfFirmenlogo);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);

        btHinzufuegen.setText("Hinzufügen");
        btHinzufuegen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onHinzufuegen(evt);
            }
        });
        getContentPane().add(btHinzufuegen);

        btAbbrechen.setText("Abbrechen");
        btAbbrechen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onAbbrechen(evt);
            }
        });
        getContentPane().add(btAbbrechen);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onHinzufuegen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onHinzufuegen
    {//GEN-HEADEREND:event_onHinzufuegen
        String name = tfFirmenname.getText();
        if(!(tfFirmenlogo.getText().equals("(Optional)")))
        {
            String logopath = tfFirmenlogo.getText();
            firma = new Firma(name, new ImageIcon(logopath));
        }else
        {
            firma = new Firma(name, new ImageIcon(System.getProperty("user.dir")+File.separator+"src"+File.separator+"logos"+File.separator+"keinlogo.png"));
        }
        isOK = true;
        this.dispose();
    }//GEN-LAST:event_onHinzufuegen

    private void onAbbrechen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onAbbrechen
    {//GEN-HEADEREND:event_onAbbrechen
        isOK = false;
        this.dispose();
    }//GEN-LAST:event_onAbbrechen

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FirmaHinzufuegenDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FirmaHinzufuegenDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FirmaHinzufuegenDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FirmaHinzufuegenDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                FirmaHinzufuegenDlg dialog = new FirmaHinzufuegenDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbbrechen;
    private javax.swing.JButton btHinzufuegen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfFirmenlogo;
    private javax.swing.JTextField tfFirmenname;
    // End of variables declaration//GEN-END:variables
}
