package gui;

import beans.Firma;
import bl.FirmaTableModel;
import bl.FirmaTableRenderer;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Enis Lushtaku
 */
public class FirmaGUI extends javax.swing.JFrame implements Runnable
{
    FirmaTableModel ftm;
    FirmaHinzufuegenDlg firmaHinzufuegenDlg;
    FirmaTableRenderer ftr;
    /**
     * Creates new form FirmaGUI
     */
    public FirmaGUI()
    {
        initComponents();
        this.setTitle("LUKO Firmenverwaltung");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        Thread t1 = new Thread(this);
        t1.start();
        ftm = new FirmaTableModel();
        taFirmen.setModel(ftm);
        ftr = new FirmaTableRenderer();
        taFirmen.setDefaultRenderer(Object.class, ftr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        laWillkommen = new javax.swing.JLabel();
        laUhrzeit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFirmen = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btFirmaHinzufuegen = new javax.swing.JButton();
        btVerwaltung = new javax.swing.JButton();
        btFirmaLoeschen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        laWillkommen.setBackground(new java.awt.Color(255, 255, 255));
        laWillkommen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        laWillkommen.setForeground(new java.awt.Color(176, 11, 11));
        laWillkommen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laWillkommen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(laWillkommen);

        laUhrzeit.setBackground(new java.awt.Color(255, 255, 255));
        laUhrzeit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        laUhrzeit.setForeground(new java.awt.Color(176, 11, 11));
        laUhrzeit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laUhrzeit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(laUhrzeit);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/mainlogoFirmenGUI.png"))); // NOI18N
        jPanel4.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        taFirmen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(taFirmen);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel1);

        btFirmaHinzufuegen.setText("Firma hinzufügen");
        btFirmaHinzufuegen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onFirmaHinzufuegen(evt);
            }
        });
        jPanel5.add(btFirmaHinzufuegen);

        btVerwaltung.setBackground(new java.awt.Color(204, 0, 0));
        btVerwaltung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btVerwaltung.setForeground(new java.awt.Color(255, 255, 255));
        btVerwaltung.setText("Verwaltung");
        btVerwaltung.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onVerwaltung(evt);
            }
        });
        jPanel5.add(btVerwaltung);

        btFirmaLoeschen.setText("Firma löschen");
        jPanel5.add(btFirmaLoeschen);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel2);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onFirmaHinzufuegen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onFirmaHinzufuegen
    {//GEN-HEADEREND:event_onFirmaHinzufuegen
        firmaHinzufuegenDlg = new FirmaHinzufuegenDlg(this, rootPaneCheckingEnabled);
        firmaHinzufuegenDlg.setVisible(true);
        if(firmaHinzufuegenDlg.getIsOK())
        {
            Firma firma = firmaHinzufuegenDlg.getFirma();
            ftm.addFirma(firma);
        }
    }//GEN-LAST:event_onFirmaHinzufuegen

    private void onVerwaltung(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onVerwaltung
    {//GEN-HEADEREND:event_onVerwaltung
        // TODO add your handling code here:
    }//GEN-LAST:event_onVerwaltung

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FirmaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FirmaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FirmaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FirmaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FirmaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFirmaHinzufuegen;
    private javax.swing.JButton btFirmaLoeschen;
    private javax.swing.JButton btVerwaltung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel laUhrzeit;
    private javax.swing.JLabel laWillkommen;
    private javax.swing.JTable taFirmen;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run()
    {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss      dd.MM.yyyy");
        int stunde = new Date().getHours();
        if (stunde >= 6 && stunde < 10)
        {
            laWillkommen.setText("Guten Morgen!");
        } else if (stunde >= 10 && stunde < 12)
        {
            laWillkommen.setText("Guten Mittag!");
        } else if (stunde >= 12 && stunde < 18)
        {
            laWillkommen.setText("Guten Nachmittag!");
        } else if (stunde >= 18 && stunde <= 24)
        {
            laWillkommen.setText("Guten Abend!");
        } else if (stunde < 6)
        {
            laWillkommen.setText("Gute Nacht!");
        }
        while (true)
        {
            try
            {
                laUhrzeit.setText(sdf.format(new Date()));
                Thread.sleep(1000);
            } catch (InterruptedException ex)
            {
            }
        }
    }
}
